# Basic Site Settings
locale       : "en-US"
title        : "Seu Nome ou Título do Site"
name         : &name "Seu Nome"
description  : &description "Uma breve descrição"

url          : https://qelvornia.online
baseurl      : ""
repository   : "QELVORNIA/qelvornia.github.io"

# Site Author (simplificado)
author:
  name     : "Seu Nome"
  bio      : "Uma breve biografia"
  location : "Sua localização"
  github   : "QELVORNIA"

# Collections (Academic Pages)
collections:
  teaching:
    output    : true
    permalink : /teaching/:path/
  publications:
    output    : true
    permalink : /publications/:path/
  portfolio:
    output    : true
    permalink : /portfolio/:path/
  talks:
    output    : true
    permalink : /talks/:path/

# Defaults for layouts
defaults:
  - scope:
      type: pages
    values:
      layout: single
      author_profile: true

# Permalinks
permalink  : /:categories/:title/
timezone   : Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Ensure content isn't ignored
markdown_ext: "md,markdown"
